// webpack/webpack-test/src/App.vue
<template>
    <div>
        <div v-for="item of musics" :key="item.id">
            <img :src="item.coverImgUrl" alt="">
            <p>{{item.name}}</p>
           
        </div>
    </div>
</template>
<script>
/* import axios from 'axios' */
export default {
    name:"App",
    data(){
        return{
            musics:[]
        }
    },
    mounted(){
        var url="https://music.aityp.com/top/playlist?cat=华语"
        this.axios(url).then(res=>{
            this.musics=res.data.playlists
        })
    }
}
</script>
<style scoped>
    
</style>

// React/react04/src/App.js
import React from 'react';
import './App.css';
import Title from './components/Title'
import axios from 'axios'
class App extends React.Component{
  constructor(props){
    super(props);
    this.state={
      playlists:[]
    }
  }
  render(){
    return (
      <div>
        <Title></Title>
        
      </div>
    )
  }
  handleDelete(id){
    console.log(id)
  }
  componentDidMount(){
     axios.get('https://music.aityp.com/top/playlist?cat=华语').then(res=>{
      this.setState({
        playlists: res.data.playlists
      })
    }) 
  }
}

export default App;
